

services:
    brevets:
        build: brevets/.
        #        command: python flask_brevets.py
        ports:
          - "5001:5000"
        depends_on:
          - mongo

    mongo:
        image: mongo:latest
        ports:
          - "27017:27017"
#        environment:
#          MONGO_INITDB_ROOT_USERNAME: root
#          MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
          - mongo-data:/data/db

volumes:
    mongo-data:
